# CMake generated Testfile for 
# Source directory: /root/ceph/src
# Build directory: /root/ceph/src
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("json_spirit")
subdirs("fmt")
subdirs("auth")
subdirs("common")
subdirs("crush")
subdirs("msg")
subdirs("arch")
subdirs("tracing")
subdirs("global")
subdirs("lua")
subdirs("cls")
subdirs("osdc")
subdirs("perfglue")
subdirs("include")
subdirs("librados")
subdirs("neorados")
subdirs("libradosstriper")
subdirs("mgr")
subdirs("pybind")
subdirs("ceph-volume")
subdirs("python-common")
subdirs("cephadm")
subdirs("mon")
subdirs("kv")
subdirs("os")
subdirs("blk")
subdirs("osd")
subdirs("mds")
subdirs("erasure-code")
subdirs("googletest")
subdirs("dmclock")
subdirs("compressor")
subdirs("tools")
subdirs("test")
subdirs("crypto")
subdirs("bash_completion")
subdirs("client")
subdirs("mount")
subdirs("journal")
subdirs("librbd")
subdirs("rbd_fuse")
subdirs("rbd_replay")
subdirs("spawn")
subdirs("key_value_store")
subdirs("rgw")
subdirs("script")
